create table if not exists public.user_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  youtube_api_key text,
  countdown_target date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.playlists (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  channel text not null,
  subject text not null check (subject in ('physics', 'chemistry', 'maths')),
  playlist_id text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.saved_lectures (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  video text not null,
  title text not null,
  channel text not null,
  thumbnail text,
  created_at timestamptz not null default now(),
  unique (user_id, video)
);

alter table public.user_settings enable row level security;
alter table public.playlists enable row level security;
alter table public.saved_lectures enable row level security;

drop policy if exists "Users manage their own settings" on public.user_settings;
create policy "Users manage their own settings"
  on public.user_settings for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users manage their own playlists" on public.playlists;
create policy "Users manage their own playlists"
  on public.playlists for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users manage their own saved lectures" on public.saved_lectures;
create policy "Users manage their own saved lectures"
  on public.saved_lectures for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
